---
- hosts: redis
  roles:
      - redis
  tags:
      - redis

- hosts: rediscluster
  roles:
      - rediscluster
  tags:
      - rediscluster

- hosts: configsvr
  roles:
      - mongodbcluster/configsvr
  tags:
      - configsvr
      - mongodbcluster

- hosts: shard
  roles:
      - mongodbcluster/shard
  tags:
      - shard
      - mongodbcluster

- hosts: router
  roles:
      - mongodbcluster/router
  tags:
      - router
      - mongodbcluster

- hosts: accountcenter
  roles:
      - accountcenter
  tags:
      - accountcenter

- hosts: gamesrv
  roles:
      - {role: gamesrv, when: inventory_hostname == serverid}
  tags:
      - gamesrv

- name: client
  hosts: gamesrv
  roles:
      - {role: client, when: inventory_hostname == serverid}
  tags:
      - client

- name: robot
  hosts: gamesrv
  roles:
      - {role: robot, when: inventory_hostname == serverid}
  tags:
      - robot
