---
- hosts: configsvr
  roles:
      - mongodbcluster/configsvr
  tags:
      - configsvr
      - mongodbcluster

- hosts: shard
  roles:
      - mongodbcluster/shard
  tags:
      - shard
      - mongodbcluster

- hosts: router
  roles:
      - mongodbcluster/router
  tags:
      - router
      - mongodbcluster


