---
- name: mkdir log in gamesrv...
  command: mkdir -p log
  args:
    chdir: "{{ggApp}}/gamesrv"
    creates: "{{ggApp}}/gamesrv/log"

- name: build gamesrv...
  command: make linux
  args:
    chdir: "{{ggApp}}/gamesrv"
    creates: "{{ggApp}}/gamesrv/skynet/skynet"

- name: link with {{inventory_hostname}}
  command: ln -s gamesrv {{inventory_hostname}}
  args:
      chdir: "{{ggApp}}"
      creates: "{{ggApp}}/{{inventory_hostname}}"
