---
- name: link with {{inventory_hostname}}
  command: ln -s gamesrv {{inventory_hostname}}
  args:
      chdir: "{{landload_workspace}}"
      creates: "{{landload_workspace}}/{{inventory_hostname}}"

- name: mkdir log...
  command: mkdir -p log
  args:
    chdir: "{{landload_workspace}}/{{inventory_hostname}}"
    creates: "{{landload_workspace}}/{{inventory_hostname}}/log"

- name: build...
  command: make linux
  args:
    chdir: "{{landload_workspace}}/{{inventory_hostname}}"
    creates: "{{landload_workspace}}/{{inventory_hostname}}/skynet/skynet"


