---
- name: include platform specific vars
  include_vars: "{{ansible_os_family}}.yml"

- name: install deps...
  with_items: "{{dep_pkgs}}"
  package:
      name: "{{item}}"
      state: present
  become: yes
  become_user: root
