---
- name: add {{openresty_install_dir}}/bin to PATH
  shell: grep {{openresty_install_dir}}/bin ~/.bashrc || echo "export PATH={{openresty_install_dir}}/bin:$PATH" >> ~/.bashrc || source ~/.bashrc
  # this will nerver report changed status
  changed_when: False

- name: mkdir logs in accountcenter...
  command: mkdir -p logs
  args:
    chdir: "{{ggApp}}/accountcenter"
    creates: "{{ggApp}}/accountcenter/logs"
